openapi: "3.0.0"
info:
  title: Learning Hinterland
  description: PBL Learning Hinterland
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
  - url: https://learning-hinterland-api.up.railway.app/api
security:
  - bearerAuth: []
paths:
  /auth/login: # OK
    post:
      description: |
        Login Test User:
        1. admin@mail.com
        2. lecturer@mail.com
        3. student@mail.com

        Password: password
      tags:
        - "Auth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: admin@mail.com
                password:
                  type: string
                  example: password
              required:
                - email
                - password
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        type: object
  /auth/me: # OK
    get:
      tags:
        - "Auth"
      security:
        - bearerAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        type: object
  /users: # OK
    get:
      tags:
        - "User"
      parameters:
        - schema:
            type: string
          in: query
          name: search
          required: false
        - schema:
            type: string
          in: query
          name: role
          description: admin, lecturer, student
          required: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        type: object
    post:
      tags:
        - "User"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Lala
                email:
                  type: string
                  example: lala@mail.com
                role:
                  type: string
                  example: student
                  description: admin, lecturer, student
                password:
                  type: string
                  example: password
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        type: object
  /users/{id}: # OK
    get:
      tags:
        - "User"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        type: object
components:
  schemas:
    AnyValue:
      anyOf:
        - type: string
        - type: number
        - type: integer
        - type: boolean
        - type: array
          items: {}
        - type: object
    BasicResponse:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
        error:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
